apiVersion: v1
kind: Service
metadata:
  name: esocks
  labels:
    app: esocks
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: esocks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esocks
  labels:
    app: esocks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: esocks
  template:
    metadata:
      labels:
        app: esocks
    spec:
      containers:
      - name: esocks
        image: caoyuwu/esocks
        ports:
        - containerPort: 80
